### ISSUE TITLE
missing value for field "icon_format" when using riven list_items

### ISSUE THREAD

**Issue by UwUham** [leonardodalinky/pywmapi#4]
i've written like 2 lines and i'm already at a bit of a standstill from an error i don't really understand lol (maybe just me not really making sense of the docs)
my code:

```
import pywmapi as wfm

wfm.rivens.list_items("braton")
```

output:
```
Traceback (most recent call last):
  File "C:\Users\Basil\AppData\Local\Programs\Python\Python310\lib\site-packages\dacite\core.py", line 72, in from_dict
    value = get_default_value_for_field(field, field_type)
  File "C:\Users\Basil\AppData\Local\Programs\Python\Python310\lib\site-packages\dacite\dataclasses.py", line 22, in get_default_value_for_field
    raise DefaultValueNotFoundError()
dacite.dataclasses.DefaultValueNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Basil\Documents\riven-price-checker.py", line 3, in <module>
    wfm.rivens.list_items("braton")
  File "C:\Users\Basil\AppData\Local\Programs\Python\Python310\lib\site-packages\pywmapi\rivens\api.py", line 29, in list_items
    return list(map(lambda x: RivenItem.from_dict(x), res.json()["payload"]["items"]))
  File "C:\Users\Basil\AppData\Local\Programs\Python\Python310\lib\site-packages\pywmapi\rivens\api.py", line 29, in <lambda>
    return list(map(lambda x: RivenItem.from_dict(x), res.json()["payload"]["items"]))
  File "C:\Users\Basil\AppData\Local\Programs\Python\Python310\lib\site-packages\pywmapi\common\models.py", line 43, in from_dict
    return cls._from_dict(d)
  File "C:\Users\Basil\AppData\Local\Programs\Python\Python310\lib\site-packages\pywmapi\common\models.py", line 51, in _from_dict
    return from_dict(data_class=cls, data=_transform_underscore(d), config=config)
  File "C:\Users\Basil\AppData\Local\Programs\Python\Python310\lib\site-packages\dacite\core.py", line 76, in from_dict
    raise MissingValueError(field.name)
```

is this a me issue or a documentation issue or is this part of the library just a bit borked

**Comment by leonardodalinky** [comment]
Sorry for not noticing this. I'll check and update soon when I'm available. PRs are also welcome! :)
